# Use an official Node.js runtime as a base image
FROM node:18.7.0
ENV NODE_ENV=development

# Set the working directory inside the container
WORKDIR /app

# Copy only package.json and package-lock.json to install dependencies
COPY ./package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application files
COPY . .

EXPOSE 3000

# Run the development server
CMD ["npm", "run", "dev", "--"]
