# Use an official Node.js runtime as a parent image
FROM node:18-alpine

# Set the working directory
WORKDIR /app

COPY --chown=1000:1000 package.json /app/
COPY --chown=1000:1000 . /app/

RUN chgrp 1000 /app
RUN chmod g+rw /app

# Clear npm cache and install dependencies
RUN npm cache clean --force && npm install

# Build the Svelte application
RUN npm run build

# Expose the port the app runs on
EXPOSE 5000

# Command to run the application
CMD ["npm", "run", "start"]