# Start from the official PostgreSQL image
FROM postgres:17.0

# Set the UID and GID you want to use
ENV USER_ID=1000
ENV GROUP_ID=1000

ARG HOMEDIR="/home/postgres_user"
ENV PGDATA="/home/postgres_user/data"

# Install necessary packages and create a non-root user and group with the specified UID:GID
RUN groupadd -g ${GROUP_ID} postgres_user
RUN useradd -m -u ${USER_ID} -g postgres_user -s /bin/bash postgres_user
RUN mkdir -p ${PGDATA}
RUN chown -R postgres_user:postgres_user ${HOMEDIR}
RUN chmod 700 ${PGDATA}

WORKDIR ${PGDATA}

# Switch to the non-root user for running PostgreSQL
USER postgres_user

# Run PostgreSQL
CMD ["postgres"]