# Start from the official PostgreSQL image
FROM postgres:latest

# Set the UID and GID you want to use
ENV USER_ID=1000
ENV GROUP_ID=1000

ARG PGDATA

# Install necessary packages and create a non-root user and group with the specified UID:GID
RUN groupadd -g ${GROUP_ID} postgres_user
RUN useradd -m -u ${USER_ID} -g postgres_user -s /bin/bash postgres_user
RUN mkdir -p ${PGDATA}
RUN chown -R postgres_user:postgres_user /home/postgres_user && \
RUN chmod 700 ${PGDATA}

# Switch to the non-root user for running PostgreSQL
USER postgres_user

# Initialize the database
RUN initdb -D $PGDATA

# Run PostgreSQL
CMD ["postgres"]