# Stage 1: Maven Build
FROM maven:3.9-eclipse-temurin-17 AS build

# Set the working directory
WORKDIR /app

# Copy the Maven project files
COPY ./pom.xml ./
COPY ./src ./src

# Build the application
RUN mvn clean package -DskipTests

# Stage 2: Runtime
FROM eclipse-temurin:17-jre

# Set the working directory
WORKDIR /app

# CA custom
COPY wild.apps.speam.montefiore.uliege.be__cacert.crt /usr/local/share/ca-certificates/
RUN update-ca-certificates && \
    keytool -import -noprompt -trustcacerts \
       -alias oc_cert \
       -file /usr/local/share/ca-certificates/wild.apps.speam.montefiore.uliege.be__cacert.crt \
       -keystore $JAVA_HOME/lib/security/cacerts \
       -storepass changeit || true

COPY --from=build /app/target/*.jar app.jar

# Expose the application port (default for Spring Boot is 8080)
EXPOSE 8080

# Run the application
ENTRYPOINT ["java", "-jar", "/app/app.jar"]
