apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: pgdata
  name: pgdata
  namespace: mdtools
spec:
  accessModes:
    - ReadWriteOnce
  securityContext:
    fsGroup: GROUP_ID
  resources:
    requests:
      storage: 2Gi
